import { Colors } from "./components/constants";

export const styles = {
	container: {
		//     width: "100vw",
		backgroundColor: Colors.background,
		backgroundImage: "radial-gradient(#2A3951, #1A2941, #0A1931)",
		position: "relative",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		overflowY: "scroll",
		overflowX: "hidden",
	},
	name: {
		fontSize: 40,
		fontWeight: "bold",
		color: "white",
	},
	bio: {
		fontSize: 20,
		fontWeight: "500",
		color: Colors.grey,
		maxWidth: 400,
	},
	navBarContainer: {
		position: "fixed",
		right: 30,
		top: 20,
		backgroundColor: "#0d1c34",
		// backdropFilter: "blur(10px)",
		maxWidth: 1000,
		height: 50,
		borderRadius: 10,
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		padding: 20,
		//     color: Colors.grey,
		justifyContent: "space-evenly",
		zIndex: 15,
		boxShadow: "0px -3px 5px #fff4,0px 5px 10px #000",
	},
	profileImage: {
		height: 250,
		width: 250,
		borderRadius: 200,
		resize: "cover",
		marginLeft: 20,
	},
	sectionTitle: {
		color: "#fff",
		fontSize: 28,
		fontWeight: "bold",
		marginLeft: 20,
		zIndex: 5,
		marginTop: 30,
		marginBottom: 10,
		textShadow: "2px 4px 5px #000",
	},
	details: {
		color: "#fff8",
		fontWeight: "500",
		fontSize: 18,
		transitionDelay: "500ms",
	},
	educationCard: {
		display: "flex",
		flexDirection: "column",
		alignSelf: "flex-start",
		paddingLeft: 20,
		padding: 20,
		borderRadius: 20,
		backgroundColor: "rgba(0,0,0,0.2)",
		// backdropFilter: "blur(5px)",
		//     margin: 20,
		zIndex: 1,
		paddingRight: 20,
		//     marginBottom: 10,
	},
	skills: {
		color: "white",
		fontSize: 18,
		marginInline: 20,
		display: "inline-block",
		marginTop: 10,
		marginBottom: 10,
		borderRadius: 10,
		backgroundColor: "rgba(0,0,0,0.3)", //
		padding: 10,
		boxShadow: "-3px -3px 5px #fff2, 4px 4px 10px #000	",
	},
	photoPreview: {
		height: 390,
		width: 390,
		position: "absolute",
		borderRadius: 20,
		// left: 100,
	},
	navHover: {
		// backgroundColor: "#7771",
		boxShadow: "0px -3px 5px #fff2,0px 3px 5px #000a",
		// backgroundImage: "linear-gradient(transparent, #0004)",
	},
};
