import { Colors } from "./components/constants";

export const styles = {
  container: {
    //     width: "100vw",
    backgroundColor: Colors.background,
    backgroundImage: "radial-gradient(#2A3951, #1A2941, #0A1931)",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    overflowY: "scroll",
    overflowX: "hidden",
  },
  name: {
    fontSize: 40,
    fontWeight: "bold",
    color: "white",
  },
  bio: {
    fontSize: 20,
    fontWeight: "500",
    color: Colors.grey,
    maxWidth: 400,
  },
  navBarContainer: {
    position: "fixed",
    right: 30,
    top: 20,
    backgroundColor: "rgba(0,0,0,0.3)",
    maxWidth: 1000,
    height: 50,
    borderRadius: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    //     color: Colors.grey,
    justifyContent: "space-evenly",
    zIndex: 15,
  },
  profileImage: {
    height: 250,
    width: 250,
    borderRadius: 200,
    resize: "cover",
    marginLeft: 20,
  },
  sectionTitle: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "bold",
    marginLeft: 20,
    zIndex: 5,
    marginTop: 30,
    marginBottom: 10,
  },
  details: {
    color: "#fff8",
    fontWeight: "500",
    fontSize: 18,
    transitionDelay: "500ms",
  },
  educationCard: {
    display: "flex",
    flexDirection: "column",
    alignSelf: "flex-start",
    paddingLeft: 20,
    padding: 20,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.2)",
    backdropFilter: "blur(5px)",
    //     margin: 20,
    zIndex: 10,
    paddingRight: 20,
    //     marginBottom: 10,
  },
  skills: {
    color: "white",
    fontSize: 18,
    marginInline: 20,
    display: "inline-block",
    marginTop: 5,
    marginBottom: 5,
    borderRadius: 10,
    backgroundColor: "rgba(0,0,0,0.3)", //
    padding: 10,
  },
};
